steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_BUILD_ID'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
      - '--build-arg'
      - 'VITE_SUPABASE_PUBLISHABLE_KEY=${_VITE_SUPABASE_PUBLISHABLE_KEY}'
      - '--build-arg'
      - 'VITE_SUPABASE_PROJECT_ID=${_VITE_SUPABASE_PROJECT_ID}'
      - '--build-arg'
      - 'JUDGE0_API_KEY=${_JUDGE0_API_KEY}'
      - '--build-arg'
      - 'JUDGE0_API_HOST=${_JUDGE0_API_HOST}'
      - '--build-arg'
      - 'JUDGE0_API_URL=${_JUDGE0_API_URL}'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_BUILD_ID'

# Default substitution values (will be overridden by pipeline)
substitutions:
  _IMAGE_NAME: 'algo-image'
  _VITE_SUPABASE_URL: ''
  _VITE_SUPABASE_PUBLISHABLE_KEY: ''
  _VITE_SUPABASE_PROJECT_ID: ''
  _JUDGE0_API_KEY: ''
  _JUDGE0_API_HOST: ''
  _JUDGE0_API_URL: ''
  _BUILD_ID: ''