// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from '@supabase/ssr';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

// Check if Supabase credentials are available
const hasSupabaseCredentials = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY;

if (!hasSupabaseCredentials) {
  console.warn('⚠️ Supabase credentials not found. Some features will be disabled.');
}

// Create a browser client that automatically handles cookies
export const supabase = hasSupabaseCredentials
  ? createBrowserClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  : null;


// Helper to check if Supabase is available
export const isSupabaseAvailable = () => supabase !== null;