// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if Supabase credentials are available
const hasSupabaseCredentials = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY;

if (!hasSupabaseCredentials) {
  console.warn('⚠️ Supabase credentials not found. User progress tracking will be disabled.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a conditional client that only initializes if credentials are available
export const supabase = hasSupabaseCredentials
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : null;

// Helper to check if Supabase is available
export const isSupabaseAvailable = () => supabase !== null;